//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::MoreMountains.Tools.AITransition))]
	public class PropertyProvider_MoreMountains_Tools_AITransition : Unity.VisualScripting.SerializedPropertyProvider<MoreMountains.Tools.AITransition>
	{
	}
}
